#!/bin/bash -e

mkdir -p deploy

required=(
  ${AUTHD_OVERLORD_DB_URL:?"missing"}
  ${AUTHD_OVERLORD_KEY_SECRET:?"missing"}
  ${AUTHD_DB_URL:?"missing"}
  ${AUTHD_KEY_SECRET:?"missing"}
)

eval "cat <<EOF
$(<static/authd.service.tmpl)
EOF
" 1> deploy/authd.service

eval "cat <<EOF
$(<static/authd-overlord.service.tmpl)
EOF
" 1> deploy/authd-overlord.service
